In [32]:
# How to view attributes in Open3D (Python):

import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud("Data/1398110231.025_ascii.pcd")
print(pcd)



PointCloud with 36723 points.


In [33]:
print(np.asarray(pcd.points))     # x, y, z
  

[[ 25.29000092 -19.54000092  15.44799995]
 [ 22.74300003 -20.44499969   6.78700018]
 [ 21.59900093 -20.92900085   2.99600005]
 ...
 [ -2.42600012   2.33899999   1.25499999]
 [ -2.17499995   2.38599992   0.95499998]
 [ -1.04700005   1.00100005   2.36899996]]


In [34]:
print(np.asarray(pcd.colors))   # rgb, if available

[]


In [35]:
# Visualizing Point Clouds in Open3D

pcd = o3d.io.read_point_cloud("Data/1398110231.025_ascii.pcd")
o3d.visualization.draw_geometries([pcd])

In [36]:
# Calculating Mean, Min, Max Coordinates

# These values help us understand the size and spread of the point cloud.

import numpy as np

points = np.asarray(pcd.points)

min_coords = points.min(axis=0)   # [min_x, min_y, min_z]
max_coords = points.max(axis=0)   # [max_x, max_y, max_z]
mean_coords = points.mean(axis=0) # [mean_x, mean_y, mean_z]

print("Min:", min_coords)
print("Max:", max_coords)
print("Mean:", mean_coords)


Min: [-44.3769989 -63.0530014  -0.866    ]
Max: [37.64899826 15.59000015 15.44799995]
Mean: [-2.74268995 -3.64932906  0.23072747]


In [37]:
# Min, Max, Mean

min_coords = points.min(axis=0)
print(min_coords)
max_coords = points.max(axis=0)
print(max_coords)
mean_coords = points.mean(axis=0)
print(mean_coords)


[-44.3769989 -63.0530014  -0.866    ]
[37.64899826 15.59000015 15.44799995]
[-2.74268995 -3.64932906  0.23072747]


In [38]:
# Scaling(min-max)
scaled_points = (points - points.min(axis=0)) / (points.max(axis=0) - points.min(axis=0))
print(scaled_points)
pcd.points = o3d.utility.Vector3dVector(scaled_points)
print(pcd.points)

[[0.84932829 0.55329781 1.        ]
 [0.81827715 0.54179013 0.4691063 ]
 [0.80433036 0.53563572 0.23672919]
 ...
 [0.5114354  0.83150439 0.13001103]
 [0.51449541 0.83210203 0.11162192]
 [0.52824715 0.8144908  0.19829594]]
std::vector<Eigen::Vector3d> with 36723 elements.
Use numpy.asarray() to access data.


In [39]:
# standardization

standardized = (points - points.mean(axis=0)) / points.std(axis=0)
print(standardized)
pcd.points = o3d.utility.Vector3dVector(standardized)


[[ 4.09632547 -2.40100716 28.05062842]
 [ 3.72414056 -2.5377483  12.08544894]
 [ 3.55697171 -2.61087864  5.09734144]
 ...
 [ 0.04627685  0.90480887  1.88808395]
 [ 0.08295468  0.91191035  1.33508151]
 [ 0.24778562  0.70264326  3.94156621]]


In [40]:
# Statistical Outlier Removal

filtered, index = pcd.remove_statistical_outlier(nb_neighbors=20, std_ratio=2.0)
o3d.visualization.draw_geometries([filtered])


In [42]:
#Normalization

# Convert to NumPy array
points = np.asarray(pcd.points)

# Center the cloud (subtract mean)
mean = points.mean(axis=0)
centered = points - mean

# Scale to unit size (divide by max distance from center)
max_range = np.abs(centered).max()
normalized = centered / max_range

# Update the point cloud with normalized points
pcd.points = o3d.utility.Vector3dVector(normalized)

# Visualize the result
o3d.visualization.draw_geometries([pcd])
